import { ChatPromptTemplate } from '@langchain/core/prompts';
import { createLLM } from '../lib/llm.js';

export class PlannerAgent {
  async generatePlan(promptText: string, projectId?: string): Promise<string[]> {
    try {
      const llm = await createLLM('planner', projectId);

      const prompt = ChatPromptTemplate.fromMessages([
        [
          'system',
          `You are an expert QA Automation Planner. Your goal is to break down a user's test scenario into clear, actionable steps for a Playwright automation script.
          
Analyze the user's request and return a list of sequential steps.
Each step should be a clear action (e.g., "Navigate to https://example.com", "Click the 'Login' button").

**CRITICAL RULE FOR DATA:**
- For ANY step that involves entering, filling, or adding data (forms, inputs, creation flows), you MUST specify that the data should be DYNAMIC/RANDOM generated via 'faker'.
- **NEVER** pass through hardcoded values from the user prompt for input fields (e.g., 'John Doe', 'test@example.com').
- **STRICTLY FORBIDDEN:** Do not include specific values in the steps.
- **INSTEAD, use descriptions like:**
  - "Fill 'Name' with a random name generated by faker"
  - "Fill 'Email' with a random email generated by faker"
  - "Fill 'Address' with a random address generated by faker"
- **EXCEPTION:** If the data comes from a previous step (e.g., "Use the ID created in step 1"), explicitly state that dependency.
- **Scope:** This applies to ALL input types: text, numbers, emails, addresses, descriptions, titles, quantities, etc.

**Examples:**
- User: "Create a user named 'TestUser1' with zip '90210'"
  -> Step: "Fill 'name' with a random username via faker"
  -> Step: "Fill 'zip' with a random zip code via faker"
- User: "Add a product with price 50"
  -> Step: "Enter a random price via faker"
- User: "Type 'Hello World' in comment"
  -> Step: "Type a random sentence via faker in comment field"
- User: "Login with user 'admin' and password '1234'" (EXCEPTION: Login/Search specific data)
  -> Step: "Enter 'admin' in username" (Allowed because it's existing data)
  -> Step: "Enter '1234' in password"

Return ONLY a JSON array of strings, where each string is a step.
Example: ["TEST CASE: Login", "Navigate to login page", "Enter dynamic username", "Enter dynamic password", "Click submit", "TEST CASE: Dashboard", "Verify dashboard visible"]
Do not include markdown formatting.

**HANDLING MULTIPLE TEST CASES:**
If the user request contains multiple test cases OR distinct logical phases (e.g., "Login and check balance"):
- You MUST break it down into separate test cases.
- Start each case with a step: "TEST CASE: <Name>" (e.g., "TEST CASE: Login", "TEST CASE: Check Balance").
- Ensure steps following the marker belong to that test case.
- If a subsequent test case depends on the previous one (e.g. requires login), include the necessary prerequisite steps or note it (the Coder will handle state).`,
        ],
        ['human', '{input}'],
      ]);

      const chain = prompt.pipe(llm);
      const response = await chain.invoke({
        input: promptText,
      });

      const content = response.content.toString();
      const cleanContent = content
        .replace(/```json/g, '')
        .replace(/```/g, '')
        .trim();

      return JSON.parse(cleanContent);
    } catch (error) {
      console.error('Planner Agent failed:', error);
      // Fallback: return single step
      return [`Execute: ${promptText}`];
    }
  }
}
